version: "3.4"
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.2
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      # DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: "text2vec-ollama,generative-ollama"
      CLUSTER_HOSTNAME: "node1"

  rag_router:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - rag_data:/app/data
    restart: always
    environment:
      WEAVIATE_HOST: "weaviate"
      WEAVIATE_COLLECTION_NAME: "Rag_demo"
    depends_on:
      - weaviate

volumes:
  weaviate_data:
  rag_data:
